# Generated by Django 4.0.2 on 2022-02-22 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xp',
            name='hero_image',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
